---
extends: airbnb-base
parser: babel-eslint
settings:
  import/resolver:
    - node
    - alias:
        - ["^~", "./server"]
parserOptions:
  sourceType: module
  allowImportExportEverywhere: false
env:
  node: true
  mocha: true
rules:
  no-underscore-dangle: 0
  class-methods-use-this: 0
  no-use-before-define:
    - error
    - functions: false
      classes: false
  arrow-parens:
    - error
    - "as-needed"
    - requireForBlockBody: false
overrides:
  - files: "**/*.test.js"
    rules:
      "no-unused-expressions": 0
