---
  extends: airbnb-base
  parser: babel-eslint
  settings:
    import/resolver:
      - node
      - eslint-import-resolver-babel-plugin-root-import
  parserOptions:
    sourceType: module
    allowImportExportEverywhere: false
  env:
    node: true
    mocha: true
  rules:
    no-underscore-dangle: 0
    class-methods-use-this: 0
    no-use-before-define:
      - error
      - functions: false
        classes: false
    arrow-parens:
      - error
      - 'as-needed'
      - requireForBlockBody: false
  overrides:
    - files: '**/*.test.js'
      rules:
        'no-unused-expressions': off
