dist: xenial
sudo: required
language: node_js
node_js:
  - "8"

env:
  global:
    - CC_TEST_REPORTER_ID=78fabb154963bab3a938a31cdec79491946a31d666044aa6024e2f0ddf1b3bd2

services:
  - docker

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run lint
  - npm run test
  - npm run build
  - ln -s docker-compose.ci.yml docker-compose.override.yml
  - docker-compose up --build -d
  - sleep 30
  - docker-compose ps
  - docker-compose logs ncodr
  - docker-compose ps ncodr 2>/dev/null | grep -qi up
  - docker-compose down

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - '[[ $TRAVIS_PULL_REQUEST = false ]] && [[ $TRAVIS_BRANCH = master ]] &&  curl --data build=true -X POST $DOCKER_URL'
  - npm run package

deploy:
  provider: releases
  api_key:
    secure: a82ExBJvRkaSq+gYKN4bGA5jtERY0pWZS2KL5aY3g6BaonIuVK3M2hjjYMa0TRGUewNNE7JnEhTmsS3JB3koPSHT3ep9UfQ3hAjh50MDEUK78htUOiozKdc6raxyE9LxGi/td/KrI6TuIaKsoY+35T5xBEKdE1ZXLnu8xcGQjmQ6a8iFwkAm6moNEyslR0xJfTMK32svpX3gs9v3sLbffRWvRCgjoOeZVz7g/XtYJESG2+oKT0aCTVvR8pGcQ2D76/bn6TlLhfhsNxfqqfgFbqtXhMnPDkRlVTi60pexvoxKoXuka4zwFSzb49qQddDw5XDuZ5TpvTF6wdwTkGYUs9Om+GwtwKf0FQ1GoZzWVXmQhujbkvwxlDNpowe+V7T9IuCvTPSbyLGKU4tqmPF3RVDZKQzg7DdCfR7KiMtxuBlRYitLJNLR8sLQ9QyGZIvXsSTVK9e+8J0li5P6L6nxF9jpRvqTdRWJdrph5mBbp2auI/wh9Q+tcK9v2bqOx4rasKajH9BCtiuIWAS8e3cRqxKKMhDuH/oxyRM4C5QXWIga+/SfRNTHj3immhJL4CUseXfDcEU6OD1OzlEojPyRoa69U0fs8Om+0i3rKKjfXT0epnn+PgBPD10te74CrLgzhzd/tPd/2zmFru1KZ9nxT2Ie4hkcYOqc2XSOAH8GF40=
  file_glob: true
  file: ncodr-*.zip
  skip_cleanup: true
  on:
    tags: true