dist: trusty
sudo: required
language: node_js
node_js:
  - "8"

services:
  - docker

script:
  - npm run compile

after_success:
  - docker build -t aztechian/ncodr:$(jq -r .version package.json) .
  - echo "would push to docker here"
