dist: trusty
sudo: required
language: node_js
node_js:
  - "8"

env:
  global:
    - CC_TEST_REPORTER_ID=78fabb154963bab3a938a31cdec79491946a31d666044aa6024e2f0ddf1b3bd2

services:
  - docker

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run lint
  - npm run test
  - npm run compile
  - docker-compose up --build -d
  - sleep 30
  - docker-compose ps ncodr | grep -qi up
  - docker-compose down

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - '[[ $TRAVIS_PULL_REQUEST = false ]] && [[ $TRAVIS_BRANCH = master ]] &&  curl --data build=true -X POST $DOCKER_URL'
