Core:
  listen: PORT
  interface: LISTEN_IP
  logLevel: LOG_LEVEL
  api: API
  ui: UI
  redis:
    host: REDIS_HOST
    port: REDIS_PORT
    password: REDIS_PASSWORD
  auth:
    type: AUTH_TYPE
    googleClientId: GOOGLE_CLIENT_ID
    googleDomain: GOOGLE_DOMAIN
Ripper:
  enable: RIP
  disc: RIPPER_DISC
  owner: RIPPER_OWNER
  group: RIPPER_GROUP
  output: RIPPER_OUTPUT
  device: RIPPER_DEVICE
  mkvKey: MAKEMKV_KEY
Encoder:
  enable: ENCODE
  owner: ENCODER_OWNER
  group: ENCODER_GROUP
  output: ENCODER_OUTPUT
  input: ENCODER_INPUT
