Core:
  listen: OPENSHIFT_NODEJS_PORT
  interface: OPENSHIFT_NODEJS_IP
  logLevel: LOG_LEVEL
  redis:
    host: REDIS_HOST
    port: REDIS_PORT
    password: REDIS_PASSWORD
Ripper:
  force: FORCE_RIP
