Core:
  listen: OPENSHIFT_NODEJS_PORT
  interface: OPENSHIFT_NODEJS_IP
  logLevel: LOG_LEVEL
  api: API
  ui: UI
  redis:
    host: REDIS_HOST
    port: REDIS_PORT
    password: REDIS_PASSWORD
  auth:
    type: AUTH_TYPE
    googleClientId: GOOGLE_CLIENT_ID
    googleDomain: GOOGLE_DOMAIN
Ripper:
  enable: RIP
  output: RIPPER_OUTPUT
  device: RIPPER_DEVICE
  mkvKey: MAKEMKV_KEY
Encoder:
  enable: ENCODE
  output: ENCODER_OUTPUT
  input: ENCODER_INPUT
