Core:
  listen: 2000
  interface: 0.0.0.0
  logLevel: info
  queues:
    - ripQ:
      description: disc ripping
    - encodeQ:
      description: video encoding
  redis:
    host: localhost
    port: 6379
    password: ''
Ripper:
  force: false
  device: /dev/sr0
  # disc: 0
  output: /rips
Encoder:
  output: /media
  hbOpts:
    - '--preset High Profile'
    - '--optimize'
    - '--quality 21'
    - '--cfr'
    - '--main-feature'
    - '--min-duration=3600'
  avOpts:
    - '-strict experimental'
    - '-c copy'
