---
Core:
  listen: 2000
  interface: 0.0.0.0
  logLevel: info
  sessionSecret: pleaseOverrideMe
  queues:
    - id: ripQ
      name: disc ripping
    - id: encodeQ
      name: video encoding
  redis:
    host: localhost
    port: 6379
    password: ''
Ripper:
  force: false
  device: /dev/sr0
  # disc: 0
  # mkvKey: abcdefg
  output: /rips
  makemkvOpts:
    - backup
    - '--decrypt'
    - '--progress=-stdout'
    - '--robot'
Encoder:
  output: /media
  input: /rips
  hbOpts:
    '--preset': High Profile
    '--optimize': ''
    '--quality': 21
    '--cfr': ''
    '--main-feature': ''
    # - '--min-duration=3600'
  avOpts:
    - '-strict experimental'
    - '-c copy'
